### ISSUE TITLE
Can't build with Qt5

### ISSUE THREAD

**Issue by gasinvein** [baumgarr/nixnote2#100]
When I'm trying to build with Qt5 (5.4.2) on Ubuntu 15.10, I get this errors:
```
../nixnote2/gui/widgetpanel.cpp: In member function ‘void WidgetPanel::dragMoveHandler(QDragMoveEvent*)’:
../nixnote2/gui/widgetpanel.cpp:174:43: error: ‘class QObject’ has no member named ‘mapToGlobal’
             int bottom = event->source()->mapToGlobal(event->source()->visibleRegion().boundingRect().bottomLeft()).y();
                                           ^
../nixnote2/gui/widgetpanel.cpp:174:72: error: ‘class QObject’ has no member named ‘visibleRegion’
             int bottom = event->source()->mapToGlobal(event->source()->visibleRegion().boundingRect().bottomLeft()).y();
                                                                        ^
../nixnote2/gui/widgetpanel.cpp:175:49: error: ‘class QObject’ has no member named ‘mapToGlobal’
             int actualBottom = event->source()->mapToGlobal(event->source()->geometry().bottomLeft()).y();
                                                 ^
../nixnote2/gui/widgetpanel.cpp:175:78: error: ‘class QObject’ has no member named ‘geometry’
             int actualBottom = event->source()->mapToGlobal(event->source()->geometry().bottomLeft()).y();
                                                                              ^
../nixnote2/gui/widgetpanel.cpp:176:82: error: ‘class QObject’ has no member named ‘geometry’
             bool bottomVisible = this->visibleRegion().contains(event->source()->geometry().bottomLeft());
                                                                                  ^
```
Am I doing something wrong?

**Comment by baumgarr** [comment]
No, I build on Qt 4.8 but another person has ported it to Qt5.  My guess is the last changes I put in place are not totally compatible with Qt5 and some "if qt5 do this but if qt4 do that" logic will be needed.

In the meantime, you can comment out everything in the dragMoveHandler function in widgetpanel.cpp.  That should allow you to compile.  You'll re-introduce a bug where dragging a large list in the left hand panel doesn't auto-scroll, but otherwise I think everything else should be fine.

**Comment by gasinvein** [comment]
Oh, understood. Then I'll use Qt4 build.
But are you planning to make a full-functional Qt5 port?

**Comment by baumgarr** [comment]
If Michael doesn't do it, then I'll eventually do it after I release the final non-beta build.  Right now I want to use Qt4 to maintain compatibility with older Linux distros that are still in use.

**Comment by michaelcadilhac** [comment]
@gasinvein Does the following fixes your problem?

```patch
diff --git a/gui/widgetpanel.cpp b/gui/widgetpanel.cpp
index b70523a..385e069 100644
--- a/gui/widgetpanel.cpp
+++ b/gui/widgetpanel.cpp
@@ -149,6 +149,7 @@ void WidgetPanel::dragEnterHandler(QDragEnterEvent *event) {
 void WidgetPanel::dragMoveHandler(QDragMoveEvent *event) {
 
    //QPoint pos = event->source()->mapToGlobal(event->pos());
+    QWidget *source = qobject_cast<QWidget *>(event->source());
     QPoint pos = QCursor::pos();
     pos = this->mapFromGlobal(pos);
     int mouse = QCursor::pos().y();
@@ -170,10 +171,10 @@ void WidgetPanel::dragMoveHandler(QDragMoveEvent *event) {
     if (pos.y()>priorMousePosition.y()) {
         timer.stop();
         scrollUp=false;
-        if (event->source()->objectName()=="Tags") {
-            int bottom = event->source()->mapToGlobal(event->source()->visibleRegion().boundingRect().bottomLeft()).y();
-            int actualBottom = event->source()->mapToGlobal(event->source()->geometry().bottomLeft()).y();
-            bool bottomVisible = this->visibleRegion().contains(event->source()->geometry().bottomLeft());
+        if (source->objectName()=="Tags") {
+            int bottom = source->mapToGlobal(source->visibleRegion().boundingRect().bottomLeft()).y();
+            int actualBottom = source->mapToGlobal(source->geometry().bottomLeft()).y();
+            bool bottomVisible = this->visibleRegion().contains(source->geometry().bottomLeft());
             if (bottom-mouse < 50 && bottom < actualBottom && !bottomVisible) {
                 timer.start(5);
             }
```

For some reasons, Qt5 `QDragEvent::source()` now returns a `QObject` rather than a `QWidget`.  This is beyond by understanding.

**Comment by gasinvein** [comment]
@michaelcadilhac Yes, now it compiles and seems to be working fine.

**Comment by baumgarr** [comment]
Thanks.  I added this & pushed out the change.
